image: gcc

stages:
  - test_style
  - build
  - unit_and_stress_tests

test_style:
  stage: test_style
  before_script:
    - apt -qq update > /dev/null && apt -qq -y install cppcheck > /dev/null
    - apt -qq -y install python-pip > /dev/null && pip install --quiet cpplint
  script:
    - ./lint.sh

build:
  stage: build
  before_script:
    - apt -qq update > /dev/null && apt -qq -y install cmake > /dev/null
  script:
    - cmake -S . -B build -DMULTITHREAD=OFF
    - cd build; make app; cd ..;
    - cmake -S . -B build -DMULTITHREAD=ON
    - cd build; make app;

unit_and_stress_tests:
  stage: unit_and_stress_tests
  before_script:
    - apt -qq update > /dev/null && apt -qq -y install cmake > /dev/null
    - apt -qq -y install valgrind > /dev/null
    - apt -qq -y install libgtest-dev > /dev/null && apt -qq -y install gcovr > /dev/null
  script:
    - cmake -S . -B build
    - cd build; make; cd ..;
    - ./unit_and_stress_tests.sh
